### PR TITLE
Add allowed mime types

### PR DESCRIPTION
**Pull request by itkg-ngilain**
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/87
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/137

### CODE REVIEW

**Comment by nicolasThal** [comment]
I would also add a configuration parameter to allow the integrator to add some accepted mime_typest

**Comment by itkg-ngilain** [comment]
@nicolasThal : The goal of this PR is to fix a dependency bug. I suggest to create a ticket for an evolution

**Comment by nicolasThal** [comment]
all right for me :+1: then

**Comment by itkg-alavieille** [comment]
:+1:

**Pull request merged**
