### PR TITLE
update node repository method names

### PR DESCRIPTION
**Pull request by nicolasThal**

### CODE REVIEW

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1090
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/440
https://github.com/open-orchestra/open-orchestra-model-interface/pull/119
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/124
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/44
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/179

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
@itkg-ngilain pr updated with the contents

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/127

**Comment by itkg-ngilain** [comment]
:+1:

**Pull request merged**
